#!/bin/bash
set -eo pipefail

# attempt to test external reachability instead of local unix socket
host="$(hostname -i || echo '127.0.0.1')"
user="${PGUSER:-postgres}"
db="postgres"
export PGPASSWORD="${POSTGRES_PASSWORD:-}"

if [ "$POSTGRES_HOST_AUTH_METHOD" != "trust" ] && [ -z "$POSTGRES_PASSWORD" ]; then
    echo "[ERROR] POSTGRES_PASSWORD is not set"
    exit 1
fi

args=(
	--host "$host"
	--username "$user"
	--dbname "$db"
	--quiet --no-align --tuples-only
)

if select="$(echo 'SELECT 1' | /usr/bin/psql "${args[@]}")" && [ "$select" = '1' ]; then
	exit 0
fi

exit 1
