version: '2.4'

networks:
  test_net:
    driver: bridge

services:

  sut:
    build: .
    command: npm run test-mongo
    environment:
      # Read password from shell environment
      - PGPASSWORD
    networks:
      - test_net
    depends_on:
      - mongo

  mongo:
    image: mongo:5.0
    networks:
      - test_net
