---
apiVersion: monitoring.gke.io/v1alpha1
kind: PodMonitor
metadata:
  name: web-monitor
  namespace: default
spec:
  selector:
    matchLabels:
      app: web
  podMetricsEndpoints:
    - port: web-port
---
apiVersion: monitoring.gke.io/v1alpha1
kind: PodMonitor
metadata:
  name: vote-monitor
  namespace: default
spec:
  selector:
    matchLabels:
      app: vote
  podMetricsEndpoints:
    - port: vote-port
